[package]
name = "nakadion"
version = "0.1.0"
authors = ["Christian Douven <chridou@users.noreply.github.com>"]
readme = "README.md"
license = "Apache-2.0/MIT"
description = "A connector for the Nakadi Event Broker"
documentation = "https://docs.rs/nakadion"
homepage = "https://github.com/chridou/nakadion"
repository = "https://github.com/chridou/nakadion"
keywords = ["event", "broker", "distributed", "message", "nakadi"]

[dependencies]
log = "0.3"
uuid = {version = "0.4", features=["serde"] }
url = { version = "1.4" }
hyper = "0.10"
hyper-native-tls = "0.2"
derive_builder = "0.4"
error-chain = "0.10"

serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dev-dependencies] 
env_logger = "0.3"
