[package]
name = "nakadion"
version = "0.1.0"
authors = ["Christian Douven <chridou@users.noreply.github.com>"]
readme = "README.md"
license = "Apache-2.0/MIT"
documentation = "https://docs.rs/nakadion"
homepage = "https://github.com/chridou/nakadion"
repository = "https://github.com/chridou/nakadion"
keywords = ["event", "broker", "distributed", "message"]

[dependencies]
uuid = "0.4"
hyper = "0.10"
derive_builder = "0.4"
error-chain = "0.10"
